# build and save build to dist

name: build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install

      - name: Create subfolder
        run: mkdir gh-pages

      - name: Copy new files for pages
        run: node ./scripts/copyDeps.js

      - name: Commit gh-pages files
        working-directory: ./gh-pages
        run: |
          git config --local user.name  ${{ github.event.pusher.name }}
          git config --local user.email  ${{ github.event.pusher.email }}
          git add .
          git commit -m "[CI] Updating github pages"

      - name: Push changes
        working-directory: ./gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "gh-pages"
          force: true